
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Item` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Item
 * 
 */
export type ItemModel = runtime.Types.Result.DefaultSelection<Prisma.$ItemPayload>

export type AggregateItem = {
  _count: ItemCountAggregateOutputType | null
  _avg: ItemAvgAggregateOutputType | null
  _sum: ItemSumAggregateOutputType | null
  _min: ItemMinAggregateOutputType | null
  _max: ItemMaxAggregateOutputType | null
}

export type ItemAvgAggregateOutputType = {
  id: number | null
  rating: number | null
  prevId: number | null
  nextId: number | null
}

export type ItemSumAggregateOutputType = {
  id: number | null
  rating: number | null
  prevId: number | null
  nextId: number | null
}

export type ItemMinAggregateOutputType = {
  id: number | null
  name: string | null
  description: string | null
  rating: number | null
  collectionId: string | null
  listId: string | null
  prevId: number | null
  nextId: number | null
}

export type ItemMaxAggregateOutputType = {
  id: number | null
  name: string | null
  description: string | null
  rating: number | null
  collectionId: string | null
  listId: string | null
  prevId: number | null
  nextId: number | null
}

export type ItemCountAggregateOutputType = {
  id: number
  name: number
  description: number
  rating: number
  collectionId: number
  listId: number
  prevId: number
  nextId: number
  _all: number
}


export type ItemAvgAggregateInputType = {
  id?: true
  rating?: true
  prevId?: true
  nextId?: true
}

export type ItemSumAggregateInputType = {
  id?: true
  rating?: true
  prevId?: true
  nextId?: true
}

export type ItemMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  rating?: true
  collectionId?: true
  listId?: true
  prevId?: true
  nextId?: true
}

export type ItemMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  rating?: true
  collectionId?: true
  listId?: true
  prevId?: true
  nextId?: true
}

export type ItemCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  rating?: true
  collectionId?: true
  listId?: true
  prevId?: true
  nextId?: true
  _all?: true
}

export type ItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Item to aggregate.
   */
  where?: Prisma.ItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Items to fetch.
   */
  orderBy?: Prisma.ItemOrderByWithRelationInput | Prisma.ItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Items
  **/
  _count?: true | ItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ItemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ItemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ItemMaxAggregateInputType
}

export type GetItemAggregateType<T extends ItemAggregateArgs> = {
      [P in keyof T & keyof AggregateItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateItem[P]>
    : Prisma.GetScalarType<T[P], AggregateItem[P]>
}




export type ItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ItemWhereInput
  orderBy?: Prisma.ItemOrderByWithAggregationInput | Prisma.ItemOrderByWithAggregationInput[]
  by: Prisma.ItemScalarFieldEnum[] | Prisma.ItemScalarFieldEnum
  having?: Prisma.ItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ItemCountAggregateInputType | true
  _avg?: ItemAvgAggregateInputType
  _sum?: ItemSumAggregateInputType
  _min?: ItemMinAggregateInputType
  _max?: ItemMaxAggregateInputType
}

export type ItemGroupByOutputType = {
  id: number
  name: string
  description: string
  rating: number | null
  collectionId: string
  listId: string
  prevId: number | null
  nextId: number | null
  _count: ItemCountAggregateOutputType | null
  _avg: ItemAvgAggregateOutputType | null
  _sum: ItemSumAggregateOutputType | null
  _min: ItemMinAggregateOutputType | null
  _max: ItemMaxAggregateOutputType | null
}

export type GetItemGroupByPayload<T extends ItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ItemGroupByOutputType[P]>
      }
    >
  >



export type ItemWhereInput = {
  AND?: Prisma.ItemWhereInput | Prisma.ItemWhereInput[]
  OR?: Prisma.ItemWhereInput[]
  NOT?: Prisma.ItemWhereInput | Prisma.ItemWhereInput[]
  id?: Prisma.IntFilter<"Item"> | number
  name?: Prisma.StringFilter<"Item"> | string
  description?: Prisma.StringFilter<"Item"> | string
  rating?: Prisma.FloatNullableFilter<"Item"> | number | null
  collectionId?: Prisma.StringFilter<"Item"> | string
  listId?: Prisma.StringFilter<"Item"> | string
  prevId?: Prisma.IntNullableFilter<"Item"> | number | null
  nextId?: Prisma.IntNullableFilter<"Item"> | number | null
  prev?: Prisma.XOR<Prisma.ItemNullableScalarRelationFilter, Prisma.ItemWhereInput> | null
  prevOf?: Prisma.XOR<Prisma.ItemNullableScalarRelationFilter, Prisma.ItemWhereInput> | null
  next?: Prisma.XOR<Prisma.ItemNullableScalarRelationFilter, Prisma.ItemWhereInput> | null
  nextOf?: Prisma.XOR<Prisma.ItemNullableScalarRelationFilter, Prisma.ItemWhereInput> | null
  collection?: Prisma.XOR<Prisma.CollectionScalarRelationFilter, Prisma.CollectionWhereInput>
  list?: Prisma.XOR<Prisma.ListScalarRelationFilter, Prisma.ListWhereInput>
}

export type ItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  rating?: Prisma.SortOrderInput | Prisma.SortOrder
  collectionId?: Prisma.SortOrder
  listId?: Prisma.SortOrder
  prevId?: Prisma.SortOrderInput | Prisma.SortOrder
  nextId?: Prisma.SortOrderInput | Prisma.SortOrder
  prev?: Prisma.ItemOrderByWithRelationInput
  prevOf?: Prisma.ItemOrderByWithRelationInput
  next?: Prisma.ItemOrderByWithRelationInput
  nextOf?: Prisma.ItemOrderByWithRelationInput
  collection?: Prisma.CollectionOrderByWithRelationInput
  list?: Prisma.ListOrderByWithRelationInput
}

export type ItemWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  prevId?: number
  nextId?: number
  AND?: Prisma.ItemWhereInput | Prisma.ItemWhereInput[]
  OR?: Prisma.ItemWhereInput[]
  NOT?: Prisma.ItemWhereInput | Prisma.ItemWhereInput[]
  name?: Prisma.StringFilter<"Item"> | string
  description?: Prisma.StringFilter<"Item"> | string
  rating?: Prisma.FloatNullableFilter<"Item"> | number | null
  collectionId?: Prisma.StringFilter<"Item"> | string
  listId?: Prisma.StringFilter<"Item"> | string
  prev?: Prisma.XOR<Prisma.ItemNullableScalarRelationFilter, Prisma.ItemWhereInput> | null
  prevOf?: Prisma.XOR<Prisma.ItemNullableScalarRelationFilter, Prisma.ItemWhereInput> | null
  next?: Prisma.XOR<Prisma.ItemNullableScalarRelationFilter, Prisma.ItemWhereInput> | null
  nextOf?: Prisma.XOR<Prisma.ItemNullableScalarRelationFilter, Prisma.ItemWhereInput> | null
  collection?: Prisma.XOR<Prisma.CollectionScalarRelationFilter, Prisma.CollectionWhereInput>
  list?: Prisma.XOR<Prisma.ListScalarRelationFilter, Prisma.ListWhereInput>
}, "id" | "prevId" | "nextId">

export type ItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  rating?: Prisma.SortOrderInput | Prisma.SortOrder
  collectionId?: Prisma.SortOrder
  listId?: Prisma.SortOrder
  prevId?: Prisma.SortOrderInput | Prisma.SortOrder
  nextId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ItemCountOrderByAggregateInput
  _avg?: Prisma.ItemAvgOrderByAggregateInput
  _max?: Prisma.ItemMaxOrderByAggregateInput
  _min?: Prisma.ItemMinOrderByAggregateInput
  _sum?: Prisma.ItemSumOrderByAggregateInput
}

export type ItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.ItemScalarWhereWithAggregatesInput | Prisma.ItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.ItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ItemScalarWhereWithAggregatesInput | Prisma.ItemScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Item"> | number
  name?: Prisma.StringWithAggregatesFilter<"Item"> | string
  description?: Prisma.StringWithAggregatesFilter<"Item"> | string
  rating?: Prisma.FloatNullableWithAggregatesFilter<"Item"> | number | null
  collectionId?: Prisma.StringWithAggregatesFilter<"Item"> | string
  listId?: Prisma.StringWithAggregatesFilter<"Item"> | string
  prevId?: Prisma.IntNullableWithAggregatesFilter<"Item"> | number | null
  nextId?: Prisma.IntNullableWithAggregatesFilter<"Item"> | number | null
}

export type ItemCreateInput = {
  name: string
  description: string
  rating?: number | null
  prev?: Prisma.ItemCreateNestedOneWithoutPrevOfInput
  prevOf?: Prisma.ItemCreateNestedOneWithoutPrevInput
  next?: Prisma.ItemCreateNestedOneWithoutNextOfInput
  nextOf?: Prisma.ItemCreateNestedOneWithoutNextInput
  collection: Prisma.CollectionCreateNestedOneWithoutItemsInput
  list: Prisma.ListCreateNestedOneWithoutItemsInput
}

export type ItemUncheckedCreateInput = {
  id?: number
  name: string
  description: string
  rating?: number | null
  collectionId: string
  listId: string
  prevId?: number | null
  nextId?: number | null
  prevOf?: Prisma.ItemUncheckedCreateNestedOneWithoutPrevInput
  nextOf?: Prisma.ItemUncheckedCreateNestedOneWithoutNextInput
}

export type ItemUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  prev?: Prisma.ItemUpdateOneWithoutPrevOfNestedInput
  prevOf?: Prisma.ItemUpdateOneWithoutPrevNestedInput
  next?: Prisma.ItemUpdateOneWithoutNextOfNestedInput
  nextOf?: Prisma.ItemUpdateOneWithoutNextNestedInput
  collection?: Prisma.CollectionUpdateOneRequiredWithoutItemsNestedInput
  list?: Prisma.ListUpdateOneRequiredWithoutItemsNestedInput
}

export type ItemUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  collectionId?: Prisma.StringFieldUpdateOperationsInput | string
  listId?: Prisma.StringFieldUpdateOperationsInput | string
  prevId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  prevOf?: Prisma.ItemUncheckedUpdateOneWithoutPrevNestedInput
  nextOf?: Prisma.ItemUncheckedUpdateOneWithoutNextNestedInput
}

export type ItemCreateManyInput = {
  id?: number
  name: string
  description: string
  rating?: number | null
  collectionId: string
  listId: string
  prevId?: number | null
  nextId?: number | null
}

export type ItemUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type ItemUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  collectionId?: Prisma.StringFieldUpdateOperationsInput | string
  listId?: Prisma.StringFieldUpdateOperationsInput | string
  prevId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ItemListRelationFilter = {
  every?: Prisma.ItemWhereInput
  some?: Prisma.ItemWhereInput
  none?: Prisma.ItemWhereInput
}

export type ItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ItemNullableScalarRelationFilter = {
  is?: Prisma.ItemWhereInput | null
  isNot?: Prisma.ItemWhereInput | null
}

export type ItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  collectionId?: Prisma.SortOrder
  listId?: Prisma.SortOrder
  prevId?: Prisma.SortOrder
  nextId?: Prisma.SortOrder
}

export type ItemAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  prevId?: Prisma.SortOrder
  nextId?: Prisma.SortOrder
}

export type ItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  collectionId?: Prisma.SortOrder
  listId?: Prisma.SortOrder
  prevId?: Prisma.SortOrder
  nextId?: Prisma.SortOrder
}

export type ItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  collectionId?: Prisma.SortOrder
  listId?: Prisma.SortOrder
  prevId?: Prisma.SortOrder
  nextId?: Prisma.SortOrder
}

export type ItemSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  prevId?: Prisma.SortOrder
  nextId?: Prisma.SortOrder
}

export type ItemCreateNestedManyWithoutCollectionInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutCollectionInput, Prisma.ItemUncheckedCreateWithoutCollectionInput> | Prisma.ItemCreateWithoutCollectionInput[] | Prisma.ItemUncheckedCreateWithoutCollectionInput[]
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutCollectionInput | Prisma.ItemCreateOrConnectWithoutCollectionInput[]
  createMany?: Prisma.ItemCreateManyCollectionInputEnvelope
  connect?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
}

export type ItemUncheckedCreateNestedManyWithoutCollectionInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutCollectionInput, Prisma.ItemUncheckedCreateWithoutCollectionInput> | Prisma.ItemCreateWithoutCollectionInput[] | Prisma.ItemUncheckedCreateWithoutCollectionInput[]
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutCollectionInput | Prisma.ItemCreateOrConnectWithoutCollectionInput[]
  createMany?: Prisma.ItemCreateManyCollectionInputEnvelope
  connect?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
}

export type ItemUpdateManyWithoutCollectionNestedInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutCollectionInput, Prisma.ItemUncheckedCreateWithoutCollectionInput> | Prisma.ItemCreateWithoutCollectionInput[] | Prisma.ItemUncheckedCreateWithoutCollectionInput[]
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutCollectionInput | Prisma.ItemCreateOrConnectWithoutCollectionInput[]
  upsert?: Prisma.ItemUpsertWithWhereUniqueWithoutCollectionInput | Prisma.ItemUpsertWithWhereUniqueWithoutCollectionInput[]
  createMany?: Prisma.ItemCreateManyCollectionInputEnvelope
  set?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
  disconnect?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
  delete?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
  connect?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
  update?: Prisma.ItemUpdateWithWhereUniqueWithoutCollectionInput | Prisma.ItemUpdateWithWhereUniqueWithoutCollectionInput[]
  updateMany?: Prisma.ItemUpdateManyWithWhereWithoutCollectionInput | Prisma.ItemUpdateManyWithWhereWithoutCollectionInput[]
  deleteMany?: Prisma.ItemScalarWhereInput | Prisma.ItemScalarWhereInput[]
}

export type ItemUncheckedUpdateManyWithoutCollectionNestedInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutCollectionInput, Prisma.ItemUncheckedCreateWithoutCollectionInput> | Prisma.ItemCreateWithoutCollectionInput[] | Prisma.ItemUncheckedCreateWithoutCollectionInput[]
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutCollectionInput | Prisma.ItemCreateOrConnectWithoutCollectionInput[]
  upsert?: Prisma.ItemUpsertWithWhereUniqueWithoutCollectionInput | Prisma.ItemUpsertWithWhereUniqueWithoutCollectionInput[]
  createMany?: Prisma.ItemCreateManyCollectionInputEnvelope
  set?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
  disconnect?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
  delete?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
  connect?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
  update?: Prisma.ItemUpdateWithWhereUniqueWithoutCollectionInput | Prisma.ItemUpdateWithWhereUniqueWithoutCollectionInput[]
  updateMany?: Prisma.ItemUpdateManyWithWhereWithoutCollectionInput | Prisma.ItemUpdateManyWithWhereWithoutCollectionInput[]
  deleteMany?: Prisma.ItemScalarWhereInput | Prisma.ItemScalarWhereInput[]
}

export type ItemCreateNestedManyWithoutListInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutListInput, Prisma.ItemUncheckedCreateWithoutListInput> | Prisma.ItemCreateWithoutListInput[] | Prisma.ItemUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutListInput | Prisma.ItemCreateOrConnectWithoutListInput[]
  createMany?: Prisma.ItemCreateManyListInputEnvelope
  connect?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
}

export type ItemUncheckedCreateNestedManyWithoutListInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutListInput, Prisma.ItemUncheckedCreateWithoutListInput> | Prisma.ItemCreateWithoutListInput[] | Prisma.ItemUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutListInput | Prisma.ItemCreateOrConnectWithoutListInput[]
  createMany?: Prisma.ItemCreateManyListInputEnvelope
  connect?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
}

export type ItemUpdateManyWithoutListNestedInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutListInput, Prisma.ItemUncheckedCreateWithoutListInput> | Prisma.ItemCreateWithoutListInput[] | Prisma.ItemUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutListInput | Prisma.ItemCreateOrConnectWithoutListInput[]
  upsert?: Prisma.ItemUpsertWithWhereUniqueWithoutListInput | Prisma.ItemUpsertWithWhereUniqueWithoutListInput[]
  createMany?: Prisma.ItemCreateManyListInputEnvelope
  set?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
  disconnect?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
  delete?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
  connect?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
  update?: Prisma.ItemUpdateWithWhereUniqueWithoutListInput | Prisma.ItemUpdateWithWhereUniqueWithoutListInput[]
  updateMany?: Prisma.ItemUpdateManyWithWhereWithoutListInput | Prisma.ItemUpdateManyWithWhereWithoutListInput[]
  deleteMany?: Prisma.ItemScalarWhereInput | Prisma.ItemScalarWhereInput[]
}

export type ItemUncheckedUpdateManyWithoutListNestedInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutListInput, Prisma.ItemUncheckedCreateWithoutListInput> | Prisma.ItemCreateWithoutListInput[] | Prisma.ItemUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutListInput | Prisma.ItemCreateOrConnectWithoutListInput[]
  upsert?: Prisma.ItemUpsertWithWhereUniqueWithoutListInput | Prisma.ItemUpsertWithWhereUniqueWithoutListInput[]
  createMany?: Prisma.ItemCreateManyListInputEnvelope
  set?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
  disconnect?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
  delete?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
  connect?: Prisma.ItemWhereUniqueInput | Prisma.ItemWhereUniqueInput[]
  update?: Prisma.ItemUpdateWithWhereUniqueWithoutListInput | Prisma.ItemUpdateWithWhereUniqueWithoutListInput[]
  updateMany?: Prisma.ItemUpdateManyWithWhereWithoutListInput | Prisma.ItemUpdateManyWithWhereWithoutListInput[]
  deleteMany?: Prisma.ItemScalarWhereInput | Prisma.ItemScalarWhereInput[]
}

export type ItemCreateNestedOneWithoutPrevOfInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutPrevOfInput, Prisma.ItemUncheckedCreateWithoutPrevOfInput>
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutPrevOfInput
  connect?: Prisma.ItemWhereUniqueInput
}

export type ItemCreateNestedOneWithoutPrevInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutPrevInput, Prisma.ItemUncheckedCreateWithoutPrevInput>
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutPrevInput
  connect?: Prisma.ItemWhereUniqueInput
}

export type ItemCreateNestedOneWithoutNextOfInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutNextOfInput, Prisma.ItemUncheckedCreateWithoutNextOfInput>
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutNextOfInput
  connect?: Prisma.ItemWhereUniqueInput
}

export type ItemCreateNestedOneWithoutNextInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutNextInput, Prisma.ItemUncheckedCreateWithoutNextInput>
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutNextInput
  connect?: Prisma.ItemWhereUniqueInput
}

export type ItemUncheckedCreateNestedOneWithoutPrevInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutPrevInput, Prisma.ItemUncheckedCreateWithoutPrevInput>
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutPrevInput
  connect?: Prisma.ItemWhereUniqueInput
}

export type ItemUncheckedCreateNestedOneWithoutNextInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutNextInput, Prisma.ItemUncheckedCreateWithoutNextInput>
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutNextInput
  connect?: Prisma.ItemWhereUniqueInput
}

export type ItemUpdateOneWithoutPrevOfNestedInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutPrevOfInput, Prisma.ItemUncheckedCreateWithoutPrevOfInput>
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutPrevOfInput
  upsert?: Prisma.ItemUpsertWithoutPrevOfInput
  disconnect?: Prisma.ItemWhereInput | boolean
  delete?: Prisma.ItemWhereInput | boolean
  connect?: Prisma.ItemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ItemUpdateToOneWithWhereWithoutPrevOfInput, Prisma.ItemUpdateWithoutPrevOfInput>, Prisma.ItemUncheckedUpdateWithoutPrevOfInput>
}

export type ItemUpdateOneWithoutPrevNestedInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutPrevInput, Prisma.ItemUncheckedCreateWithoutPrevInput>
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutPrevInput
  upsert?: Prisma.ItemUpsertWithoutPrevInput
  disconnect?: Prisma.ItemWhereInput | boolean
  delete?: Prisma.ItemWhereInput | boolean
  connect?: Prisma.ItemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ItemUpdateToOneWithWhereWithoutPrevInput, Prisma.ItemUpdateWithoutPrevInput>, Prisma.ItemUncheckedUpdateWithoutPrevInput>
}

export type ItemUpdateOneWithoutNextOfNestedInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutNextOfInput, Prisma.ItemUncheckedCreateWithoutNextOfInput>
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutNextOfInput
  upsert?: Prisma.ItemUpsertWithoutNextOfInput
  disconnect?: Prisma.ItemWhereInput | boolean
  delete?: Prisma.ItemWhereInput | boolean
  connect?: Prisma.ItemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ItemUpdateToOneWithWhereWithoutNextOfInput, Prisma.ItemUpdateWithoutNextOfInput>, Prisma.ItemUncheckedUpdateWithoutNextOfInput>
}

export type ItemUpdateOneWithoutNextNestedInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutNextInput, Prisma.ItemUncheckedCreateWithoutNextInput>
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutNextInput
  upsert?: Prisma.ItemUpsertWithoutNextInput
  disconnect?: Prisma.ItemWhereInput | boolean
  delete?: Prisma.ItemWhereInput | boolean
  connect?: Prisma.ItemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ItemUpdateToOneWithWhereWithoutNextInput, Prisma.ItemUpdateWithoutNextInput>, Prisma.ItemUncheckedUpdateWithoutNextInput>
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ItemUncheckedUpdateOneWithoutPrevNestedInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutPrevInput, Prisma.ItemUncheckedCreateWithoutPrevInput>
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutPrevInput
  upsert?: Prisma.ItemUpsertWithoutPrevInput
  disconnect?: Prisma.ItemWhereInput | boolean
  delete?: Prisma.ItemWhereInput | boolean
  connect?: Prisma.ItemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ItemUpdateToOneWithWhereWithoutPrevInput, Prisma.ItemUpdateWithoutPrevInput>, Prisma.ItemUncheckedUpdateWithoutPrevInput>
}

export type ItemUncheckedUpdateOneWithoutNextNestedInput = {
  create?: Prisma.XOR<Prisma.ItemCreateWithoutNextInput, Prisma.ItemUncheckedCreateWithoutNextInput>
  connectOrCreate?: Prisma.ItemCreateOrConnectWithoutNextInput
  upsert?: Prisma.ItemUpsertWithoutNextInput
  disconnect?: Prisma.ItemWhereInput | boolean
  delete?: Prisma.ItemWhereInput | boolean
  connect?: Prisma.ItemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ItemUpdateToOneWithWhereWithoutNextInput, Prisma.ItemUpdateWithoutNextInput>, Prisma.ItemUncheckedUpdateWithoutNextInput>
}

export type ItemCreateWithoutCollectionInput = {
  name: string
  description: string
  rating?: number | null
  prev?: Prisma.ItemCreateNestedOneWithoutPrevOfInput
  prevOf?: Prisma.ItemCreateNestedOneWithoutPrevInput
  next?: Prisma.ItemCreateNestedOneWithoutNextOfInput
  nextOf?: Prisma.ItemCreateNestedOneWithoutNextInput
  list: Prisma.ListCreateNestedOneWithoutItemsInput
}

export type ItemUncheckedCreateWithoutCollectionInput = {
  id?: number
  name: string
  description: string
  rating?: number | null
  listId: string
  prevId?: number | null
  nextId?: number | null
  prevOf?: Prisma.ItemUncheckedCreateNestedOneWithoutPrevInput
  nextOf?: Prisma.ItemUncheckedCreateNestedOneWithoutNextInput
}

export type ItemCreateOrConnectWithoutCollectionInput = {
  where: Prisma.ItemWhereUniqueInput
  create: Prisma.XOR<Prisma.ItemCreateWithoutCollectionInput, Prisma.ItemUncheckedCreateWithoutCollectionInput>
}

export type ItemCreateManyCollectionInputEnvelope = {
  data: Prisma.ItemCreateManyCollectionInput | Prisma.ItemCreateManyCollectionInput[]
}

export type ItemUpsertWithWhereUniqueWithoutCollectionInput = {
  where: Prisma.ItemWhereUniqueInput
  update: Prisma.XOR<Prisma.ItemUpdateWithoutCollectionInput, Prisma.ItemUncheckedUpdateWithoutCollectionInput>
  create: Prisma.XOR<Prisma.ItemCreateWithoutCollectionInput, Prisma.ItemUncheckedCreateWithoutCollectionInput>
}

export type ItemUpdateWithWhereUniqueWithoutCollectionInput = {
  where: Prisma.ItemWhereUniqueInput
  data: Prisma.XOR<Prisma.ItemUpdateWithoutCollectionInput, Prisma.ItemUncheckedUpdateWithoutCollectionInput>
}

export type ItemUpdateManyWithWhereWithoutCollectionInput = {
  where: Prisma.ItemScalarWhereInput
  data: Prisma.XOR<Prisma.ItemUpdateManyMutationInput, Prisma.ItemUncheckedUpdateManyWithoutCollectionInput>
}

export type ItemScalarWhereInput = {
  AND?: Prisma.ItemScalarWhereInput | Prisma.ItemScalarWhereInput[]
  OR?: Prisma.ItemScalarWhereInput[]
  NOT?: Prisma.ItemScalarWhereInput | Prisma.ItemScalarWhereInput[]
  id?: Prisma.IntFilter<"Item"> | number
  name?: Prisma.StringFilter<"Item"> | string
  description?: Prisma.StringFilter<"Item"> | string
  rating?: Prisma.FloatNullableFilter<"Item"> | number | null
  collectionId?: Prisma.StringFilter<"Item"> | string
  listId?: Prisma.StringFilter<"Item"> | string
  prevId?: Prisma.IntNullableFilter<"Item"> | number | null
  nextId?: Prisma.IntNullableFilter<"Item"> | number | null
}

export type ItemCreateWithoutListInput = {
  name: string
  description: string
  rating?: number | null
  prev?: Prisma.ItemCreateNestedOneWithoutPrevOfInput
  prevOf?: Prisma.ItemCreateNestedOneWithoutPrevInput
  next?: Prisma.ItemCreateNestedOneWithoutNextOfInput
  nextOf?: Prisma.ItemCreateNestedOneWithoutNextInput
  collection: Prisma.CollectionCreateNestedOneWithoutItemsInput
}

export type ItemUncheckedCreateWithoutListInput = {
  id?: number
  name: string
  description: string
  rating?: number | null
  collectionId: string
  prevId?: number | null
  nextId?: number | null
  prevOf?: Prisma.ItemUncheckedCreateNestedOneWithoutPrevInput
  nextOf?: Prisma.ItemUncheckedCreateNestedOneWithoutNextInput
}

export type ItemCreateOrConnectWithoutListInput = {
  where: Prisma.ItemWhereUniqueInput
  create: Prisma.XOR<Prisma.ItemCreateWithoutListInput, Prisma.ItemUncheckedCreateWithoutListInput>
}

export type ItemCreateManyListInputEnvelope = {
  data: Prisma.ItemCreateManyListInput | Prisma.ItemCreateManyListInput[]
}

export type ItemUpsertWithWhereUniqueWithoutListInput = {
  where: Prisma.ItemWhereUniqueInput
  update: Prisma.XOR<Prisma.ItemUpdateWithoutListInput, Prisma.ItemUncheckedUpdateWithoutListInput>
  create: Prisma.XOR<Prisma.ItemCreateWithoutListInput, Prisma.ItemUncheckedCreateWithoutListInput>
}

export type ItemUpdateWithWhereUniqueWithoutListInput = {
  where: Prisma.ItemWhereUniqueInput
  data: Prisma.XOR<Prisma.ItemUpdateWithoutListInput, Prisma.ItemUncheckedUpdateWithoutListInput>
}

export type ItemUpdateManyWithWhereWithoutListInput = {
  where: Prisma.ItemScalarWhereInput
  data: Prisma.XOR<Prisma.ItemUpdateManyMutationInput, Prisma.ItemUncheckedUpdateManyWithoutListInput>
}

export type ItemCreateWithoutPrevOfInput = {
  name: string
  description: string
  rating?: number | null
  prev?: Prisma.ItemCreateNestedOneWithoutPrevOfInput
  next?: Prisma.ItemCreateNestedOneWithoutNextOfInput
  nextOf?: Prisma.ItemCreateNestedOneWithoutNextInput
  collection: Prisma.CollectionCreateNestedOneWithoutItemsInput
  list: Prisma.ListCreateNestedOneWithoutItemsInput
}

export type ItemUncheckedCreateWithoutPrevOfInput = {
  id?: number
  name: string
  description: string
  rating?: number | null
  collectionId: string
  listId: string
  prevId?: number | null
  nextId?: number | null
  nextOf?: Prisma.ItemUncheckedCreateNestedOneWithoutNextInput
}

export type ItemCreateOrConnectWithoutPrevOfInput = {
  where: Prisma.ItemWhereUniqueInput
  create: Prisma.XOR<Prisma.ItemCreateWithoutPrevOfInput, Prisma.ItemUncheckedCreateWithoutPrevOfInput>
}

export type ItemCreateWithoutPrevInput = {
  name: string
  description: string
  rating?: number | null
  prevOf?: Prisma.ItemCreateNestedOneWithoutPrevInput
  next?: Prisma.ItemCreateNestedOneWithoutNextOfInput
  nextOf?: Prisma.ItemCreateNestedOneWithoutNextInput
  collection: Prisma.CollectionCreateNestedOneWithoutItemsInput
  list: Prisma.ListCreateNestedOneWithoutItemsInput
}

export type ItemUncheckedCreateWithoutPrevInput = {
  id?: number
  name: string
  description: string
  rating?: number | null
  collectionId: string
  listId: string
  nextId?: number | null
  prevOf?: Prisma.ItemUncheckedCreateNestedOneWithoutPrevInput
  nextOf?: Prisma.ItemUncheckedCreateNestedOneWithoutNextInput
}

export type ItemCreateOrConnectWithoutPrevInput = {
  where: Prisma.ItemWhereUniqueInput
  create: Prisma.XOR<Prisma.ItemCreateWithoutPrevInput, Prisma.ItemUncheckedCreateWithoutPrevInput>
}

export type ItemCreateWithoutNextOfInput = {
  name: string
  description: string
  rating?: number | null
  prev?: Prisma.ItemCreateNestedOneWithoutPrevOfInput
  prevOf?: Prisma.ItemCreateNestedOneWithoutPrevInput
  next?: Prisma.ItemCreateNestedOneWithoutNextOfInput
  collection: Prisma.CollectionCreateNestedOneWithoutItemsInput
  list: Prisma.ListCreateNestedOneWithoutItemsInput
}

export type ItemUncheckedCreateWithoutNextOfInput = {
  id?: number
  name: string
  description: string
  rating?: number | null
  collectionId: string
  listId: string
  prevId?: number | null
  nextId?: number | null
  prevOf?: Prisma.ItemUncheckedCreateNestedOneWithoutPrevInput
}

export type ItemCreateOrConnectWithoutNextOfInput = {
  where: Prisma.ItemWhereUniqueInput
  create: Prisma.XOR<Prisma.ItemCreateWithoutNextOfInput, Prisma.ItemUncheckedCreateWithoutNextOfInput>
}

export type ItemCreateWithoutNextInput = {
  name: string
  description: string
  rating?: number | null
  prev?: Prisma.ItemCreateNestedOneWithoutPrevOfInput
  prevOf?: Prisma.ItemCreateNestedOneWithoutPrevInput
  nextOf?: Prisma.ItemCreateNestedOneWithoutNextInput
  collection: Prisma.CollectionCreateNestedOneWithoutItemsInput
  list: Prisma.ListCreateNestedOneWithoutItemsInput
}

export type ItemUncheckedCreateWithoutNextInput = {
  id?: number
  name: string
  description: string
  rating?: number | null
  collectionId: string
  listId: string
  prevId?: number | null
  prevOf?: Prisma.ItemUncheckedCreateNestedOneWithoutPrevInput
  nextOf?: Prisma.ItemUncheckedCreateNestedOneWithoutNextInput
}

export type ItemCreateOrConnectWithoutNextInput = {
  where: Prisma.ItemWhereUniqueInput
  create: Prisma.XOR<Prisma.ItemCreateWithoutNextInput, Prisma.ItemUncheckedCreateWithoutNextInput>
}

export type ItemUpsertWithoutPrevOfInput = {
  update: Prisma.XOR<Prisma.ItemUpdateWithoutPrevOfInput, Prisma.ItemUncheckedUpdateWithoutPrevOfInput>
  create: Prisma.XOR<Prisma.ItemCreateWithoutPrevOfInput, Prisma.ItemUncheckedCreateWithoutPrevOfInput>
  where?: Prisma.ItemWhereInput
}

export type ItemUpdateToOneWithWhereWithoutPrevOfInput = {
  where?: Prisma.ItemWhereInput
  data: Prisma.XOR<Prisma.ItemUpdateWithoutPrevOfInput, Prisma.ItemUncheckedUpdateWithoutPrevOfInput>
}

export type ItemUpdateWithoutPrevOfInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  prev?: Prisma.ItemUpdateOneWithoutPrevOfNestedInput
  next?: Prisma.ItemUpdateOneWithoutNextOfNestedInput
  nextOf?: Prisma.ItemUpdateOneWithoutNextNestedInput
  collection?: Prisma.CollectionUpdateOneRequiredWithoutItemsNestedInput
  list?: Prisma.ListUpdateOneRequiredWithoutItemsNestedInput
}

export type ItemUncheckedUpdateWithoutPrevOfInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  collectionId?: Prisma.StringFieldUpdateOperationsInput | string
  listId?: Prisma.StringFieldUpdateOperationsInput | string
  prevId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nextOf?: Prisma.ItemUncheckedUpdateOneWithoutNextNestedInput
}

export type ItemUpsertWithoutPrevInput = {
  update: Prisma.XOR<Prisma.ItemUpdateWithoutPrevInput, Prisma.ItemUncheckedUpdateWithoutPrevInput>
  create: Prisma.XOR<Prisma.ItemCreateWithoutPrevInput, Prisma.ItemUncheckedCreateWithoutPrevInput>
  where?: Prisma.ItemWhereInput
}

export type ItemUpdateToOneWithWhereWithoutPrevInput = {
  where?: Prisma.ItemWhereInput
  data: Prisma.XOR<Prisma.ItemUpdateWithoutPrevInput, Prisma.ItemUncheckedUpdateWithoutPrevInput>
}

export type ItemUpdateWithoutPrevInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  prevOf?: Prisma.ItemUpdateOneWithoutPrevNestedInput
  next?: Prisma.ItemUpdateOneWithoutNextOfNestedInput
  nextOf?: Prisma.ItemUpdateOneWithoutNextNestedInput
  collection?: Prisma.CollectionUpdateOneRequiredWithoutItemsNestedInput
  list?: Prisma.ListUpdateOneRequiredWithoutItemsNestedInput
}

export type ItemUncheckedUpdateWithoutPrevInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  collectionId?: Prisma.StringFieldUpdateOperationsInput | string
  listId?: Prisma.StringFieldUpdateOperationsInput | string
  nextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  prevOf?: Prisma.ItemUncheckedUpdateOneWithoutPrevNestedInput
  nextOf?: Prisma.ItemUncheckedUpdateOneWithoutNextNestedInput
}

export type ItemUpsertWithoutNextOfInput = {
  update: Prisma.XOR<Prisma.ItemUpdateWithoutNextOfInput, Prisma.ItemUncheckedUpdateWithoutNextOfInput>
  create: Prisma.XOR<Prisma.ItemCreateWithoutNextOfInput, Prisma.ItemUncheckedCreateWithoutNextOfInput>
  where?: Prisma.ItemWhereInput
}

export type ItemUpdateToOneWithWhereWithoutNextOfInput = {
  where?: Prisma.ItemWhereInput
  data: Prisma.XOR<Prisma.ItemUpdateWithoutNextOfInput, Prisma.ItemUncheckedUpdateWithoutNextOfInput>
}

export type ItemUpdateWithoutNextOfInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  prev?: Prisma.ItemUpdateOneWithoutPrevOfNestedInput
  prevOf?: Prisma.ItemUpdateOneWithoutPrevNestedInput
  next?: Prisma.ItemUpdateOneWithoutNextOfNestedInput
  collection?: Prisma.CollectionUpdateOneRequiredWithoutItemsNestedInput
  list?: Prisma.ListUpdateOneRequiredWithoutItemsNestedInput
}

export type ItemUncheckedUpdateWithoutNextOfInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  collectionId?: Prisma.StringFieldUpdateOperationsInput | string
  listId?: Prisma.StringFieldUpdateOperationsInput | string
  prevId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  prevOf?: Prisma.ItemUncheckedUpdateOneWithoutPrevNestedInput
}

export type ItemUpsertWithoutNextInput = {
  update: Prisma.XOR<Prisma.ItemUpdateWithoutNextInput, Prisma.ItemUncheckedUpdateWithoutNextInput>
  create: Prisma.XOR<Prisma.ItemCreateWithoutNextInput, Prisma.ItemUncheckedCreateWithoutNextInput>
  where?: Prisma.ItemWhereInput
}

export type ItemUpdateToOneWithWhereWithoutNextInput = {
  where?: Prisma.ItemWhereInput
  data: Prisma.XOR<Prisma.ItemUpdateWithoutNextInput, Prisma.ItemUncheckedUpdateWithoutNextInput>
}

export type ItemUpdateWithoutNextInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  prev?: Prisma.ItemUpdateOneWithoutPrevOfNestedInput
  prevOf?: Prisma.ItemUpdateOneWithoutPrevNestedInput
  nextOf?: Prisma.ItemUpdateOneWithoutNextNestedInput
  collection?: Prisma.CollectionUpdateOneRequiredWithoutItemsNestedInput
  list?: Prisma.ListUpdateOneRequiredWithoutItemsNestedInput
}

export type ItemUncheckedUpdateWithoutNextInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  collectionId?: Prisma.StringFieldUpdateOperationsInput | string
  listId?: Prisma.StringFieldUpdateOperationsInput | string
  prevId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  prevOf?: Prisma.ItemUncheckedUpdateOneWithoutPrevNestedInput
  nextOf?: Prisma.ItemUncheckedUpdateOneWithoutNextNestedInput
}

export type ItemCreateManyCollectionInput = {
  id?: number
  name: string
  description: string
  rating?: number | null
  listId: string
  prevId?: number | null
  nextId?: number | null
}

export type ItemUpdateWithoutCollectionInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  prev?: Prisma.ItemUpdateOneWithoutPrevOfNestedInput
  prevOf?: Prisma.ItemUpdateOneWithoutPrevNestedInput
  next?: Prisma.ItemUpdateOneWithoutNextOfNestedInput
  nextOf?: Prisma.ItemUpdateOneWithoutNextNestedInput
  list?: Prisma.ListUpdateOneRequiredWithoutItemsNestedInput
}

export type ItemUncheckedUpdateWithoutCollectionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  listId?: Prisma.StringFieldUpdateOperationsInput | string
  prevId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  prevOf?: Prisma.ItemUncheckedUpdateOneWithoutPrevNestedInput
  nextOf?: Prisma.ItemUncheckedUpdateOneWithoutNextNestedInput
}

export type ItemUncheckedUpdateManyWithoutCollectionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  listId?: Prisma.StringFieldUpdateOperationsInput | string
  prevId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ItemCreateManyListInput = {
  id?: number
  name: string
  description: string
  rating?: number | null
  collectionId: string
  prevId?: number | null
  nextId?: number | null
}

export type ItemUpdateWithoutListInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  prev?: Prisma.ItemUpdateOneWithoutPrevOfNestedInput
  prevOf?: Prisma.ItemUpdateOneWithoutPrevNestedInput
  next?: Prisma.ItemUpdateOneWithoutNextOfNestedInput
  nextOf?: Prisma.ItemUpdateOneWithoutNextNestedInput
  collection?: Prisma.CollectionUpdateOneRequiredWithoutItemsNestedInput
}

export type ItemUncheckedUpdateWithoutListInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  collectionId?: Prisma.StringFieldUpdateOperationsInput | string
  prevId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  prevOf?: Prisma.ItemUncheckedUpdateOneWithoutPrevNestedInput
  nextOf?: Prisma.ItemUncheckedUpdateOneWithoutNextNestedInput
}

export type ItemUncheckedUpdateManyWithoutListInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  collectionId?: Prisma.StringFieldUpdateOperationsInput | string
  prevId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nextId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}



export type ItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  rating?: boolean
  collectionId?: boolean
  listId?: boolean
  prevId?: boolean
  nextId?: boolean
  prev?: boolean | Prisma.Item$prevArgs<ExtArgs>
  prevOf?: boolean | Prisma.Item$prevOfArgs<ExtArgs>
  next?: boolean | Prisma.Item$nextArgs<ExtArgs>
  nextOf?: boolean | Prisma.Item$nextOfArgs<ExtArgs>
  collection?: boolean | Prisma.CollectionDefaultArgs<ExtArgs>
  list?: boolean | Prisma.ListDefaultArgs<ExtArgs>
}, ExtArgs["result"]["item"]>

export type ItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  rating?: boolean
  collectionId?: boolean
  listId?: boolean
  prevId?: boolean
  nextId?: boolean
  prev?: boolean | Prisma.Item$prevArgs<ExtArgs>
  next?: boolean | Prisma.Item$nextArgs<ExtArgs>
  collection?: boolean | Prisma.CollectionDefaultArgs<ExtArgs>
  list?: boolean | Prisma.ListDefaultArgs<ExtArgs>
}, ExtArgs["result"]["item"]>

export type ItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  rating?: boolean
  collectionId?: boolean
  listId?: boolean
  prevId?: boolean
  nextId?: boolean
  prev?: boolean | Prisma.Item$prevArgs<ExtArgs>
  next?: boolean | Prisma.Item$nextArgs<ExtArgs>
  collection?: boolean | Prisma.CollectionDefaultArgs<ExtArgs>
  list?: boolean | Prisma.ListDefaultArgs<ExtArgs>
}, ExtArgs["result"]["item"]>

export type ItemSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  rating?: boolean
  collectionId?: boolean
  listId?: boolean
  prevId?: boolean
  nextId?: boolean
}

export type ItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "rating" | "collectionId" | "listId" | "prevId" | "nextId", ExtArgs["result"]["item"]>
export type ItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  prev?: boolean | Prisma.Item$prevArgs<ExtArgs>
  prevOf?: boolean | Prisma.Item$prevOfArgs<ExtArgs>
  next?: boolean | Prisma.Item$nextArgs<ExtArgs>
  nextOf?: boolean | Prisma.Item$nextOfArgs<ExtArgs>
  collection?: boolean | Prisma.CollectionDefaultArgs<ExtArgs>
  list?: boolean | Prisma.ListDefaultArgs<ExtArgs>
}
export type ItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  prev?: boolean | Prisma.Item$prevArgs<ExtArgs>
  next?: boolean | Prisma.Item$nextArgs<ExtArgs>
  collection?: boolean | Prisma.CollectionDefaultArgs<ExtArgs>
  list?: boolean | Prisma.ListDefaultArgs<ExtArgs>
}
export type ItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  prev?: boolean | Prisma.Item$prevArgs<ExtArgs>
  next?: boolean | Prisma.Item$nextArgs<ExtArgs>
  collection?: boolean | Prisma.CollectionDefaultArgs<ExtArgs>
  list?: boolean | Prisma.ListDefaultArgs<ExtArgs>
}

export type $ItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Item"
  objects: {
    prev: Prisma.$ItemPayload<ExtArgs> | null
    prevOf: Prisma.$ItemPayload<ExtArgs> | null
    next: Prisma.$ItemPayload<ExtArgs> | null
    nextOf: Prisma.$ItemPayload<ExtArgs> | null
    collection: Prisma.$CollectionPayload<ExtArgs>
    list: Prisma.$ListPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    description: string
    /**
     * Computed from linked-list position within the list's startingRating
     */
    rating: number | null
    collectionId: string
    listId: string
    /**
     * ID of the item that comes immediately before this one in the list (null = head)
     */
    prevId: number | null
    /**
     * ID of the item that comes immediately after this one in the list (null = tail)
     */
    nextId: number | null
  }, ExtArgs["result"]["item"]>
  composites: {}
}

export type ItemGetPayload<S extends boolean | null | undefined | ItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ItemPayload, S>

export type ItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ItemCountAggregateInputType | true
  }

export interface ItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Item'], meta: { name: 'Item' } }
  /**
   * Find zero or one Item that matches the filter.
   * @param {ItemFindUniqueArgs} args - Arguments to find a Item
   * @example
   * // Get one Item
   * const item = await prisma.item.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ItemFindUniqueArgs>(args: Prisma.SelectSubset<T, ItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ItemClient<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Item that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ItemFindUniqueOrThrowArgs} args - Arguments to find a Item
   * @example
   * // Get one Item
   * const item = await prisma.item.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ItemClient<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Item that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemFindFirstArgs} args - Arguments to find a Item
   * @example
   * // Get one Item
   * const item = await prisma.item.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ItemFindFirstArgs>(args?: Prisma.SelectSubset<T, ItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__ItemClient<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Item that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemFindFirstOrThrowArgs} args - Arguments to find a Item
   * @example
   * // Get one Item
   * const item = await prisma.item.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ItemClient<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Items that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Items
   * const items = await prisma.item.findMany()
   * 
   * // Get first 10 Items
   * const items = await prisma.item.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const itemWithIdOnly = await prisma.item.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ItemFindManyArgs>(args?: Prisma.SelectSubset<T, ItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Item.
   * @param {ItemCreateArgs} args - Arguments to create a Item.
   * @example
   * // Create one Item
   * const Item = await prisma.item.create({
   *   data: {
   *     // ... data to create a Item
   *   }
   * })
   * 
   */
  create<T extends ItemCreateArgs>(args: Prisma.SelectSubset<T, ItemCreateArgs<ExtArgs>>): Prisma.Prisma__ItemClient<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Items.
   * @param {ItemCreateManyArgs} args - Arguments to create many Items.
   * @example
   * // Create many Items
   * const item = await prisma.item.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ItemCreateManyArgs>(args?: Prisma.SelectSubset<T, ItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Items and returns the data saved in the database.
   * @param {ItemCreateManyAndReturnArgs} args - Arguments to create many Items.
   * @example
   * // Create many Items
   * const item = await prisma.item.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Items and only return the `id`
   * const itemWithIdOnly = await prisma.item.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Item.
   * @param {ItemDeleteArgs} args - Arguments to delete one Item.
   * @example
   * // Delete one Item
   * const Item = await prisma.item.delete({
   *   where: {
   *     // ... filter to delete one Item
   *   }
   * })
   * 
   */
  delete<T extends ItemDeleteArgs>(args: Prisma.SelectSubset<T, ItemDeleteArgs<ExtArgs>>): Prisma.Prisma__ItemClient<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Item.
   * @param {ItemUpdateArgs} args - Arguments to update one Item.
   * @example
   * // Update one Item
   * const item = await prisma.item.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ItemUpdateArgs>(args: Prisma.SelectSubset<T, ItemUpdateArgs<ExtArgs>>): Prisma.Prisma__ItemClient<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Items.
   * @param {ItemDeleteManyArgs} args - Arguments to filter Items to delete.
   * @example
   * // Delete a few Items
   * const { count } = await prisma.item.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, ItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Items.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Items
   * const item = await prisma.item.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ItemUpdateManyArgs>(args: Prisma.SelectSubset<T, ItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Items and returns the data updated in the database.
   * @param {ItemUpdateManyAndReturnArgs} args - Arguments to update many Items.
   * @example
   * // Update many Items
   * const item = await prisma.item.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Items and only return the `id`
   * const itemWithIdOnly = await prisma.item.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Item.
   * @param {ItemUpsertArgs} args - Arguments to update or create a Item.
   * @example
   * // Update or create a Item
   * const item = await prisma.item.upsert({
   *   create: {
   *     // ... data to create a Item
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Item we want to update
   *   }
   * })
   */
  upsert<T extends ItemUpsertArgs>(args: Prisma.SelectSubset<T, ItemUpsertArgs<ExtArgs>>): Prisma.Prisma__ItemClient<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Items.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemCountArgs} args - Arguments to filter Items to count.
   * @example
   * // Count the number of Items
   * const count = await prisma.item.count({
   *   where: {
   *     // ... the filter for the Items we want to count
   *   }
   * })
  **/
  count<T extends ItemCountArgs>(
    args?: Prisma.Subset<T, ItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Item.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ItemAggregateArgs>(args: Prisma.Subset<T, ItemAggregateArgs>): Prisma.PrismaPromise<GetItemAggregateType<T>>

  /**
   * Group by Item.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ItemGroupByArgs['orderBy'] }
      : { orderBy?: ItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Item model
 */
readonly fields: ItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Item.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  prev<T extends Prisma.Item$prevArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Item$prevArgs<ExtArgs>>): Prisma.Prisma__ItemClient<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  prevOf<T extends Prisma.Item$prevOfArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Item$prevOfArgs<ExtArgs>>): Prisma.Prisma__ItemClient<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  next<T extends Prisma.Item$nextArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Item$nextArgs<ExtArgs>>): Prisma.Prisma__ItemClient<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  nextOf<T extends Prisma.Item$nextOfArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Item$nextOfArgs<ExtArgs>>): Prisma.Prisma__ItemClient<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  collection<T extends Prisma.CollectionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CollectionDefaultArgs<ExtArgs>>): Prisma.Prisma__CollectionClient<runtime.Types.Result.GetResult<Prisma.$CollectionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  list<T extends Prisma.ListDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ListDefaultArgs<ExtArgs>>): Prisma.Prisma__ListClient<runtime.Types.Result.GetResult<Prisma.$ListPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Item model
 */
export interface ItemFieldRefs {
  readonly id: Prisma.FieldRef<"Item", 'Int'>
  readonly name: Prisma.FieldRef<"Item", 'String'>
  readonly description: Prisma.FieldRef<"Item", 'String'>
  readonly rating: Prisma.FieldRef<"Item", 'Float'>
  readonly collectionId: Prisma.FieldRef<"Item", 'String'>
  readonly listId: Prisma.FieldRef<"Item", 'String'>
  readonly prevId: Prisma.FieldRef<"Item", 'Int'>
  readonly nextId: Prisma.FieldRef<"Item", 'Int'>
}
    

// Custom InputTypes
/**
 * Item findUnique
 */
export type ItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemInclude<ExtArgs> | null
  /**
   * Filter, which Item to fetch.
   */
  where: Prisma.ItemWhereUniqueInput
}

/**
 * Item findUniqueOrThrow
 */
export type ItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemInclude<ExtArgs> | null
  /**
   * Filter, which Item to fetch.
   */
  where: Prisma.ItemWhereUniqueInput
}

/**
 * Item findFirst
 */
export type ItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemInclude<ExtArgs> | null
  /**
   * Filter, which Item to fetch.
   */
  where?: Prisma.ItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Items to fetch.
   */
  orderBy?: Prisma.ItemOrderByWithRelationInput | Prisma.ItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Items.
   */
  cursor?: Prisma.ItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Items.
   */
  distinct?: Prisma.ItemScalarFieldEnum | Prisma.ItemScalarFieldEnum[]
}

/**
 * Item findFirstOrThrow
 */
export type ItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemInclude<ExtArgs> | null
  /**
   * Filter, which Item to fetch.
   */
  where?: Prisma.ItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Items to fetch.
   */
  orderBy?: Prisma.ItemOrderByWithRelationInput | Prisma.ItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Items.
   */
  cursor?: Prisma.ItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Items.
   */
  distinct?: Prisma.ItemScalarFieldEnum | Prisma.ItemScalarFieldEnum[]
}

/**
 * Item findMany
 */
export type ItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemInclude<ExtArgs> | null
  /**
   * Filter, which Items to fetch.
   */
  where?: Prisma.ItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Items to fetch.
   */
  orderBy?: Prisma.ItemOrderByWithRelationInput | Prisma.ItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Items.
   */
  cursor?: Prisma.ItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Items.
   */
  distinct?: Prisma.ItemScalarFieldEnum | Prisma.ItemScalarFieldEnum[]
}

/**
 * Item create
 */
export type ItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemInclude<ExtArgs> | null
  /**
   * The data needed to create a Item.
   */
  data: Prisma.XOR<Prisma.ItemCreateInput, Prisma.ItemUncheckedCreateInput>
}

/**
 * Item createMany
 */
export type ItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Items.
   */
  data: Prisma.ItemCreateManyInput | Prisma.ItemCreateManyInput[]
}

/**
 * Item createManyAndReturn
 */
export type ItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * The data used to create many Items.
   */
  data: Prisma.ItemCreateManyInput | Prisma.ItemCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Item update
 */
export type ItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemInclude<ExtArgs> | null
  /**
   * The data needed to update a Item.
   */
  data: Prisma.XOR<Prisma.ItemUpdateInput, Prisma.ItemUncheckedUpdateInput>
  /**
   * Choose, which Item to update.
   */
  where: Prisma.ItemWhereUniqueInput
}

/**
 * Item updateMany
 */
export type ItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Items.
   */
  data: Prisma.XOR<Prisma.ItemUpdateManyMutationInput, Prisma.ItemUncheckedUpdateManyInput>
  /**
   * Filter which Items to update
   */
  where?: Prisma.ItemWhereInput
  /**
   * Limit how many Items to update.
   */
  limit?: number
}

/**
 * Item updateManyAndReturn
 */
export type ItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * The data used to update Items.
   */
  data: Prisma.XOR<Prisma.ItemUpdateManyMutationInput, Prisma.ItemUncheckedUpdateManyInput>
  /**
   * Filter which Items to update
   */
  where?: Prisma.ItemWhereInput
  /**
   * Limit how many Items to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Item upsert
 */
export type ItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemInclude<ExtArgs> | null
  /**
   * The filter to search for the Item to update in case it exists.
   */
  where: Prisma.ItemWhereUniqueInput
  /**
   * In case the Item found by the `where` argument doesn't exist, create a new Item with this data.
   */
  create: Prisma.XOR<Prisma.ItemCreateInput, Prisma.ItemUncheckedCreateInput>
  /**
   * In case the Item was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ItemUpdateInput, Prisma.ItemUncheckedUpdateInput>
}

/**
 * Item delete
 */
export type ItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemInclude<ExtArgs> | null
  /**
   * Filter which Item to delete.
   */
  where: Prisma.ItemWhereUniqueInput
}

/**
 * Item deleteMany
 */
export type ItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Items to delete
   */
  where?: Prisma.ItemWhereInput
  /**
   * Limit how many Items to delete.
   */
  limit?: number
}

/**
 * Item.prev
 */
export type Item$prevArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemInclude<ExtArgs> | null
  where?: Prisma.ItemWhereInput
}

/**
 * Item.prevOf
 */
export type Item$prevOfArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemInclude<ExtArgs> | null
  where?: Prisma.ItemWhereInput
}

/**
 * Item.next
 */
export type Item$nextArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemInclude<ExtArgs> | null
  where?: Prisma.ItemWhereInput
}

/**
 * Item.nextOf
 */
export type Item$nextOfArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemInclude<ExtArgs> | null
  where?: Prisma.ItemWhereInput
}

/**
 * Item without action
 */
export type ItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemInclude<ExtArgs> | null
}
