### GET all items in a collection
GET https://{{host}}:{{$dotenv PORT}}/{{version}}/collections/{{collectionId}}/items HTTP/1.1
Content-Type: application/json
Authorization: token {{$dotenv TOKEN}}


### GET items filtered by list
GET https://{{host}}:{{$dotenv PORT}}/{{version}}/collections/{{collectionId}}/items?listId={{listId}} HTTP/1.1
Content-Type: application/json
Authorization: token {{$dotenv TOKEN}}


### POST create item
POST https://{{host}}:{{$dotenv PORT}}/{{version}}/collections/{{collectionId}}/items HTTP/1.1
Content-Type: application/json
Authorization: token {{$dotenv TOKEN}}

{
    "name": "The Dark Knight",
    "description": "2008 superhero film directed by Christopher Nolan",
    "listId": "{{listId}}"
}


### POST create item with explicit order
POST https://{{host}}:{{$dotenv PORT}}/{{version}}/collections/{{collectionId}}/items HTTP/1.1
Content-Type: application/json
Authorization: token {{$dotenv TOKEN}}

{
    "name": "Inception",
    "description": "2010 science fiction film",
    "listId": "{{listId}}",
    "order": 1
}


### PATCH update item name/description
PATCH https://{{host}}:{{$dotenv PORT}}/{{version}}/collections/{{collectionId}}/items/{{itemId}} HTTP/1.1
Content-Type: application/json
Authorization: token {{$dotenv TOKEN}}

{
    "name": "The Dark Knight Rises",
    "description": "2012 superhero film directed by Christopher Nolan"
}


### PATCH move item to a different list at a specific position
PATCH https://{{host}}:{{$dotenv PORT}}/{{version}}/collections/{{collectionId}}/items/{{itemId}}/move HTTP/1.1
Content-Type: application/json
Authorization: token {{$dotenv TOKEN}}

{
    "listId": "{{targetListId}}",
    "order": 1
}


### DELETE item
DELETE https://{{host}}:{{$dotenv PORT}}/{{version}}/collections/{{collectionId}}/items/{{itemId}} HTTP/1.1
Content-Type: application/json
Authorization: token {{$dotenv TOKEN}}
