### GET all items in a collection (returned in linked-list order per list)
GET https://{{host}}:{{$dotenv PORT}}/{{version}}/collections/{{collectionId}}/items HTTP/1.1
Content-Type: application/json
Authorization: token {{$dotenv TOKEN}}


### GET items filtered by list (returned in linked-list order)
GET https://{{host}}:{{$dotenv PORT}}/{{version}}/collections/{{collectionId}}/items?listId={{listId}} HTTP/1.1
Content-Type: application/json
Authorization: token {{$dotenv TOKEN}}


### POST create item at tail of list (afterId omitted = append at tail; null = insert at head)
POST https://{{host}}:{{$dotenv PORT}}/{{version}}/collections/{{collectionId}}/items HTTP/1.1
Content-Type: application/json
Authorization: token {{$dotenv TOKEN}}

{
    "name": "The Dark Knight",
    "description": "2008 superhero film directed by Christopher Nolan",
    "listId": "{{listId}}"
}


### POST create item at head of list (afterId: null)
POST https://{{host}}:{{$dotenv PORT}}/{{version}}/collections/{{collectionId}}/items HTTP/1.1
Content-Type: application/json
Authorization: token {{$dotenv TOKEN}}

{
    "name": "Inception",
    "description": "2010 science fiction film",
    "listId": "{{listId}}",
    "afterId": null
}


### POST create item after a specific item
POST https://{{host}}:{{$dotenv PORT}}/{{version}}/collections/{{collectionId}}/items HTTP/1.1
Content-Type: application/json
Authorization: token {{$dotenv TOKEN}}

{
    "name": "Interstellar",
    "description": "2014 science fiction film",
    "listId": "{{listId}}",
    "afterId": {{itemId}}
}


### PATCH update item name/description
PATCH https://{{host}}:{{$dotenv PORT}}/{{version}}/collections/{{collectionId}}/items/{{itemId}} HTTP/1.1
Content-Type: application/json
Authorization: token {{$dotenv TOKEN}}

{
    "name": "The Dark Knight Rises",
    "description": "2012 superhero film directed by Christopher Nolan"
}


### PATCH move item to head of a list
PATCH https://{{host}}:{{$dotenv PORT}}/{{version}}/collections/{{collectionId}}/items/{{itemId}}/move HTTP/1.1
Content-Type: application/json
Authorization: token {{$dotenv TOKEN}}

{
    "listId": "{{targetListId}}",
    "afterId": null
}


### PATCH move item after a specific item in a list
PATCH https://{{host}}:{{$dotenv PORT}}/{{version}}/collections/{{collectionId}}/items/{{itemId}}/move HTTP/1.1
Content-Type: application/json
Authorization: token {{$dotenv TOKEN}}

{
    "listId": "{{targetListId}}",
    "afterId": {{afterItemId}}
}


### DELETE item
DELETE https://{{host}}:{{$dotenv PORT}}/{{version}}/collections/{{collectionId}}/items/{{itemId}} HTTP/1.1
Content-Type: application/json
Authorization: token {{$dotenv TOKEN}}
